"""accuracy col

Revision ID: 6edb15af462f
Revises: 06283a690312
Create Date: 2021-05-12 21:23:01.078355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edb15af462f'
down_revision = '06283a690312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('accuracy', sa.Float(), nullable=True))
    op.create_index(op.f('ix_score_accuracy'), 'score', ['accuracy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_accuracy'), table_name='score')
    op.drop_column('score', 'accuracy')
    # ### end Alembic commands ###
