"""accuracy col

Revision ID: eb23f3d6bc0d
Revises: 6edb15af462f
Create Date: 2021-05-12 21:31:22.672921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb23f3d6bc0d'
down_revision = '6edb15af462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'username')
    # ### end Alembic commands ###
